org.gradle.jvmargs=-Xmx2G -Dsodium.checks.issue2561=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=supplemental_patches
mod.name=Supplemental Patches
mod.group=io.github.jedlimlx
mod.version=1.0.0
mod.channel_tag=-beta
mod.authors=lemon41625
mod.contributors=chililisoup, mpustovoi
mod.license=MIT
mod.description=Euphoria Patches add-on that enables users to create custom shaders for modded blocks, entities, items, particles, etc, through a resource-pack.

mod.sources_url=https://github.com/jedlimlx/supplemental-patches
mod.homepage_url=https://supplemental-patches.pages.dev
mod.issues_url=https://github.com/jedlimlx/supplemental-patches/issues

deps.complementary=https://cdn.modrinth.com/data/HVnmMxH1/versions/836bPNGo/ComplementaryReimagined_r5.7.1.zip

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

deps.fabric-lang-kotlin=1.13.7+kotlin.2.2.21
deps.kotlinforforge=[VERSIONED]

deps.euphoria-patches=1.8.6-r5.7.1

deps.modmenu=[VERSIONED]
